flags: {}
extra-package-dbs: []
packages:
- '.'
- ../hhep.git/
- ../atlas.git/
- ../ttree.git/
- ../histogram-extras.git/
extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
- list-transformer-1.0.1
resolver: lts-8.0
